url:              http://localhost:4000


 # For Google Authorship https://plus.google.com/authorship
  google_plus:""   

# Analytics and webmaster tools stuff goes here
google_analytics: ""
google_verify: "" 
   